# Generated by Django 3.2.4 on 2021-06-24 12:00

from django.contrib.postgres.operations import HStoreExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        HStoreExtension(),
        UnaccentExtension(),
    ]
